### GET all configurations
GET http://localhost:8000/api/configuration/
Accept: application/json

### GET configuration by id
# @name social
GET http://localhost:8000/api/configuration/social-media-manager
Accept: application/json

### Set default configuration
PUT http://localhost:8000/api/configuration/default/social-media-manager
Content-Type: application/json


### Delete configuration by id
DELETE http://localhost:8000/api/configuration/social-media-manager

### PUT Request with additional headers
POST http://localhost:8000/api/configuration/
Content-Type: text/plain

< ./voice/voice.prompty

### PUT Edit configuration by id
PUT http://localhost:8000/api/configuration/social-media-manager
Content-Type: text/plain

< ./voice/voice.prompty

### DELETE Request Example
DELETE http://localhost:8000/api/items/3